# Generated by Django 3.0.1 on 2019-12-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionHistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='date and time')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='total')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_historical_data', to='locations.Location')),
            ],
            options={
                'default_related_name': 'consumption_historical_data',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='date and time')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='total')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_forecasts', to='locations.Location')),
            ],
            options={
                'default_related_name': 'consumption_forecasts',
            },
        ),
    ]
