# Generated by Django 3.0.1 on 2019-12-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consumptionforecast',
            constraint=models.UniqueConstraint(fields=('datetime', 'location'), name='unique_consumption_forecast'),
        ),
        migrations.AddConstraint(
            model_name='consumptionhistoricaldata',
            constraint=models.UniqueConstraint(fields=('datetime', 'location'), name='unique_consumption_historical_data'),
        ),
    ]
