# Generated by Django 3.0.1 on 2019-12-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='date and time')),
                ('bioenergy', models.PositiveIntegerField(blank=True, null=True, verbose_name='bioenergy')),
                ('hydro', models.PositiveIntegerField(blank=True, null=True, verbose_name='hydro')),
                ('nuclear', models.PositiveIntegerField(blank=True, null=True, verbose_name='nuclear')),
                ('pumped', models.PositiveIntegerField(blank=True, null=True, verbose_name='pumped')),
                ('solar', models.PositiveIntegerField(blank=True, null=True, verbose_name='solar')),
                ('thermal', models.PositiveIntegerField(blank=True, null=True, verbose_name='thermal')),
                ('wind', models.PositiveIntegerField(blank=True, null=True, verbose_name='wind')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='total')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_historical_data', to='locations.Location')),
            ],
            options={
                'default_related_name': 'production_historical_data',
            },
        ),
    ]
