# Generated by Django 3.0.1 on 2019-12-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionhistoricaldata',
            constraint=models.UniqueConstraint(fields=('datetime', 'location'), name='unique_production_historical_data'),
        ),
    ]
